### PR TITLE
play: wire up stdin to qemu to make serial work

### PR DESCRIPTION
**Pull request by stapelberg**
With this change:

1. gokrazy’s serial port starts working in qemu,
   i.e. you can press Enter and get a shell prompt.

2. qemu’s monitor key bindings start working,
   i.e. you don’t quit using Ctrl+C, but by using Ctrl+a x

### CODE REVIEW

**Comment by stapelberg** [comment]
@damdo I find myself wishing for an easy way to run gokrazy instances in qemu more and more. Aside from this PR, do you mind if I merged some of gom into a `gok qemu` subcommand?

**Comment by damdo** [comment]
Hey @stapelberg, yes for sure, it'd be awesome to have gom into gok, that was my plan all along!
What parts of it would you like to include?
I should be able to help with this in a bit

**Comment by stapelberg** [comment]
> Hey @stapelberg, yes for sure, it'd be awesome to have gom into gok, that was my plan all along!
> What parts of it would you like to include?
> I should be able to help with this in a bit

Cool!

I think the first milestone I would want to see is a command to build and run the specified gokrazy instance in a VM. 

Conceptually, I’d suggest a “vm” subcommand in gok, which can then have its own subcommands. I suggest “run” as the first subcommand. The vm subcommand would be in the “deploy and update” group.

So, `gok vm run` should build the instance and execute qemu with the right flags. We can then expand from there, but I think that’s the least controversial and most useful thing in the whole VM space. 

Out of scope for now: deploying VMs to services, both commerial (e.g. Google Cloud, AWS, Azure) or self-hosted (e.g. Proxmox). We can add that later, perhaps as a command that requires additional installation if you want to target a specific VM service provider (similar to the OCI plugin approach).

**Comment by stapelberg** [comment]
> So, `gok vm run` should build the instance and execute qemu with the right flags. We can then expand from there, but I think that’s the least controversial and most useful thing in the whole VM space.

FYI, I have submitted a `gok vm run` implementation with commit https://github.com/gokrazy/tools/commit/b8ffcd451e68c9554b766b0f57a6de4256130508

Next up is including the EFI firmware (like you did) and then we can expand from there :)

**Pull request merged**
